const ARTICLES = [
    { slug: 'i-will-fucking-piledrive-you-if-you-mention-ai-again', title: 'I Will Fucking Piledrive You If You Mention AI Again', meta: 'Ludicity · Aug 2026', time: '23:41' },
    { slug: 'the-worlds-left-to-conquer', title: 'The Worlds Left To Conquer', meta: 'Ludicity · Aug 2026', time: '12:31' },
    { slug: 'asteroid-hitting-frontend-web-development', title: 'The asteroid currently hitting frontend web development', meta: 'Nolan Lawson · Aug 2026', time: '14:44' },
    { slug: 'harnesses-are-situated-agents', title: 'Harnesses are Situated Agents', meta: 'Drew Breunig · Aug 2026', time: '4:23' },
    { slug: 'manage-your-agents-loadout-with-dr-skill', title: 'Manage Your Agent’s Loadout with Dr. Skill', meta: 'Drew Breunig · Aug 2026', time: '3:23' },
    { slug: 'ai-ecosystem-pace-layers', title: 'Understanding the Dynamics of the AI Ecosystem with Pace Layers', meta: 'Drew Breunig · Aug 2026', time: '4:28' },
    { slug: 'the-problem-is-prompt-debt', title: 'The Problem is Prompt Debt', meta: 'Drew Breunig · Aug 2026', time: '8:51' },
    { slug: 'good-writing-is-obvious-not-original', title: 'Good writing is obvious, not original', meta: 'Sean Goedecke · Aug 2026', time: '4:57' },
    { slug: 'what-is-a-harness', title: 'What is a Harness?', meta: 'Earendil · Aug 2026', time: '10:09' },
    { slug: 'ai-slop-isnt-a-model-problem-treat-your-codebase-as-a-black-box', title: 'AI slop isn\'t a model problem — treat your codebase as a black box', meta: 'David Zhang (@dzhng) · Aug 2026', time: '12:36' },
    { slug: 'extensible-software-in-the-age-of-llms', title: 'Extensible Software in the age of LLMs', meta: 'Jeremy Morrell · Aug 2026', time: '29:19' },
    { slug: 'ai-coding-insights', title: 'The Specification Is Not a Document', meta: 'leaflet.pub · Aug 2026', time: '33:39' },
    { slug: 'compaction-in-pi', title: 'How Compaction Works in Pi', meta: 'Earendil · Aug 2026', time: '6:19' },
    { slug: 'compression-is-prediction', title: 'Compression is Prediction', meta: 'ngrok Blog · Aug 2026', time: '21:53' },
    { slug: 'why-go-is-an-ideal-language-for-ai-assisted-software-engineering', title: 'Why Go is an Ideal Language for AI-Assisted Software Engineering', meta: 'Google Developers Blog · Aug 2026', time: '14:55' },
    { slug: 'when-does-a-specification-become-a-program', title: 'When Does a Specification Become a Program?', meta: 'Chad Fowler · Aug 2026', time: '20:08' },
    { slug: 'tdd-inside-the-agent-loop', title: 'TDD inside the agent loop - theater or actual value?', meta: 'Birgitta Böckeler · Aug 2025', time: '30:50' },
    { slug: 'no-local-models-will-not-win', title: 'No, local models will not win', meta: 'Sean Goedecke · Aug 2026', time: '8:38' },
    { slug: 'futzing-fraction', title: 'The Futzing Fraction', meta: 'Glyph · Aug 2025', time: '34:00' },
    { slug: 'the-dark-night-of-mathematics', title: 'The Dark Night of Mathematics', meta: 'Kirwin Hampshire · Aug 2026', time: '6:41' },
    { slug: 'luddites-and-ai-datacenters', title: 'Blood in the datacenter', meta: 'Sean Goedecke · Aug 2026', time: '18:05' },
    { slug: 'anti-ai-nostalgia', title: 'Anti-AI nostalgia and the cult of the past', meta: 'Sean Goedecke · Aug 2026', time: '13:43' },
    { slug: 'the-just-say-no-engineer-was-a-zirp-phenomenon', title: 'The just-say-no engineer was a ZIRP phenomenon', meta: 'Sean Goedecke · Aug 2026', time: '13:16' },
    { slug: 'how-to-influence-politics', title: 'How I influence tech company politics', meta: 'Sean Goedecke · Aug 2026', time: '10:18' },
    { slug: 'seeing-like-a-software-company', title: 'Seeing like a software company', meta: 'Sean Goedecke · Aug 2026', time: '24:46' },
    { slug: 'code-was-never-the-hard-part-is-an-insult-to-all-programmers', title: '"Code was never the hard part" is an insult to all programmers', meta: 'Senko Rašić · Aug 2026', time: '8:31' },
    { slug: 'fragments-august-4-martin-fowler', title: 'Fragments: August 4', meta: 'Martin Fowler · Aug 2026', time: '9:03' },
    { slug: 'pi-minimal-and-performant', title: 'Pi, Minimal and Performant', meta: 'Earendil · Aug 2026', time: '5:54' },
    { slug: 'shape-of-things-to-come-part-1', title: 'The Shape of Things to Come, Part 1', meta: 'Steve Yegge · Aug 2026', time: '39:20' },
    { slug: 'flat-curve-society', title: 'The Flat Curve Society', meta: 'Steve Yegge · Aug 2026', time: '26:18' },
    { slug: 'model-welfare-for-agentic-engineers', title: 'The Shape of Things to Come, Part 2: Model Welfare for Agentic Engineers', meta: 'Steve Yegge · 2026', time: '14:33' },
    { slug: 'claude-is-not-a-compiler', title: 'Claude Is Not a Compiler', meta: 'Josh Bleecher Snyder · Aug 2026', time: '10:42' },
    { slug: 'we-are-not-cleared-for-takeoff', title: 'We Are Not Cleared for Takeoff. Yet.', meta: 'Ian Butler · Aug 2026', time: '2:37' },
    { slug: 'the-economic-benefit-of-refactoring', title: 'The Economic Benefit of Refactoring', meta: 'Martin Fowler · Jul 2026', time: '30:18' },
    { slug: 'should-you-use-ai-for-a-task-heres-a-simple-way-to-decide', title: 'Should You Use AI for a Task? Here\'s a Simple Way to Decide', meta: 'Bruce Schneier · Jul 2026', time: '6:23' },
    { slug: 'agents-are-hard', title: 'Agent Design Is Still Hard', meta: 'Armin Ronacher · Nov 2025', time: '12:51' },
    { slug: 'superlogical', title: 'Superlogical', meta: 'Mitchell Hashimoto · Jul 2025', time: '5:05' },
    { slug: 'how-i-almost-lost-my-hands', title: 'How I almost lost my hands', meta: 'Jason Wei · Jul 2026', time: '11:24' },
    { slug: 'anthropics-position-on-open-weight-models', title: 'Our position on open-weights models', meta: 'Dario Amodei · Jul 2026', time: '8:09' },
    { slug: 'harness-engineering', title: 'Harness engineering for coding agent users', meta: 'Birgitta Böckeler · Jul 2026', time: '16:05' },
    { slug: 'the-real-ai-risk-is-inside-the-labs', title: 'The real AI risk is inside the labs', meta: 'Salvatore Sanfilippo · Jul 2026', time: '6:42' },
    { slug: 'context-anchoring', title: 'Context Anchoring', meta: 'Rahul Garg · Jul 2026', time: '16:05' },
    { slug: 'should-still-design-code-humans', title: 'Should we still design code for humans?', meta: 'Valentina Servile · Jul 2026', time: '20:40' },
    { slug: 'how-coding-agents-read-your-code', title: 'How coding agents read your code (and how to write for them)', meta: 'Ben Vinegar · Jul 2026', time: '37:04' },
    { slug: 'protecting-floss-commons-from-llms', title: 'Protecting our FLOSS commons from LLMs', meta: 'Codeberg · Jul 2026', time: '13:28' },
    { slug: 'self-hosting-deepseek-v4-flash', title: 'How we self-host DeepSeek V4 Flash on AWS spot instances', meta: 'Miguel Salinas · Jul 2026', time: '10:06' },
    { slug: 'prompt-caching', title: 'Prompt Caching In Agents', meta: 'Earendil · Jul 2026', time: '19:47' },
    { slug: 'the-future-worth-building-is-human', title: 'The Future Worth Building Is Human', meta: 'Thinking Machines Lab · Jul 2026', time: '13:02' },
    { slug: 'ai-making', title: 'On Making', meta: 'Beej · Jul 2026', time: '14:54' },
    { slug: 'practical-astar', title: 'Practical A*', meta: 'Gabriel Gambetta · Jul 2026', time: '5:24' },
    { slug: 'search-strategies', title: 'Search Strategies', meta: 'Gabriel Gambetta · Jul 2026', time: '3:45' },
    { slug: 'generic-search', title: 'Generic Search', meta: 'Gabriel Gambetta · Jul 2026', time: '7:02' },
    { slug: 'astar-demystified', title: 'A* Demystified', meta: 'Gabriel Gambetta · Jul 2026', time: '4:12' },
    { slug: 'old-and-new-apps-via-modern-coding-agents', title: 'Old and new apps, via modern coding agents', meta: 'Terence Tao · July 2026', time: '3:56' },
    { slug: 'pace-layers-and-ai-integration', title: 'Pace Layers and AI Integration', meta: 'Chad Fowler · December 2025 · ~12 min listen', time: '11:40' },
    { slug: 'the-death-and-rebirth-of-programming', title: 'The Death and Rebirth of Programming', meta: 'Chad Fowler · December 2025 · ~7 min listen', time: '7:05' },
    { slug: '2x-nine-months-later-we-did-it', title: '2× – nine months later: We did it', meta: 'Darragh Curran · April 2026', time: '15:22' },
    { slug: 'own-the-outer-loop', title: 'Own the Outer Loop', meta: 'Addy Osmani · July 2026 · ~2 min listen', time: '2:02' },
    { slug: 'viability-of-local-models-for-coding', title: 'Viability of local models for coding', meta: 'Birgitta Böckeler · Martin Fowler · July 2026', time: '11:51' },
    { slug: 'software-design-in-the-agentic-age', title: 'Software Design in the Agentic Age: Place Your Bets', meta: 'Mathias Verraes · July 2026', time: '4:02' },
    { slug: 'feedback-flywheel', title: 'Feedback Flywheel', meta: 'Rahul Garg · April 2026', time: '17:05' },
    { slug: 'the-primitive-is-the-product', title: 'The primitive is the product', meta: 'Lenny Pruss · June 2025', time: '9:47' },
    { slug: 'on-idea-generation', title: 'one must imagine sisyphus full of ideas: on exercising the idea muscle', meta: 'Sankalp · Jun 2026', time: '23:30' },
    { slug: 'prompt-injection-as-role-confusion', title: 'A Theory of Prompt Injection (and Why You Should Study Roles)', meta: 'Charles Ye et al. · June 2026', time: '9:45' },
    { slug: 'why-ai-hasnt-replaced-software-engineers', title: 'Why AI Hasnt Replaced Software Engineers', meta: 'Normal Tech · Jun 2026', time: '27:50' },
    { slug: 'agent-context', title: 'Agent Context', meta: 'Sankalp · June 2026', time: '6:21' },
    { slug: 'policy-on-the-ai-exponential', title: 'Policy on the AI Exponential', meta: 'Dario Amodei · June 2026', time: '16:47' },
    { slug: 'loop-engineering', title: 'Loop Engineering', meta: 'Addy Osmani · June 2026', time: '10:40' },
    { slug: 'my-ai-adoption-journey', title: 'My AI Adoption Journey', meta: 'Mitchell Hashimoto · 2025 · 11 min', time: '10:47' },
    { slug: 'what-is-code', title: 'What Is Code?', meta: 'Srujana Pundi · May 2026', time: '7:50' },
    { slug: 'conductors-to-orchestrators', title: 'Conductors to Orchestrators: The Future of Agentic Coding', meta: 'Addy Osmani · November 2025', time: '27:39' },
    { slug: 'absurd-workflows', title: 'Absurd Workflows: Durable Execution With Just Postgres', meta: 'Armin Ronacher · November 2025', time: '3:39' },
    { slug: 'syntaqlite-ai', title: 'Eight Years of Wanting, Three Months of Building with AI', meta: 'Lalit Maganti · April 2026', time: '20:40' },
    { slug: 'components-of-a-coding-agent', title: 'Components of A Coding Agent', meta: 'Sebastian Raschka · April 2026', time: '11:59' },
];
