const ARTICLES = [
    { slug: 'pace-layers-and-ai-integration', title: 'Pace Layers and AI Integration', meta: 'Chad Fowler · December 2025 · ~12 min listen', time: '11:40' },
    { slug: 'the-death-and-rebirth-of-programming', title: 'The Death and Rebirth of Programming', meta: 'Chad Fowler · December 2025 · ~7 min listen', time: '7:05' },
    { slug: '2x-nine-months-later-we-did-it', title: '2× – nine months later: We did it', meta: 'Darragh Curran · April 2026', time: '15:22' },
    { slug: 'coding-as-craft-going-back-to-the-old-gym', title: 'Coding as Craft: Going Back to the Old Gym', meta: 'Christian Ekrem · April 2025 · ~8 min listen', time: '8:19' },
    { slug: 'own-the-outer-loop', title: 'Own the Outer Loop', meta: 'Addy Osmani · July 2026 · ~2 min listen', time: '2:02' },
    { slug: 'viability-of-local-models-for-coding', title: 'Viability of local models for coding', meta: 'Birgitta Böckeler · Martin Fowler · July 2026', time: '11:51' },
    { slug: 'software-design-in-the-agentic-age', title: 'Software Design in the Agentic Age: Place Your Bets', meta: 'Mathias Verraes · July 2026', time: '4:02' },
    { slug: 'feedback-flywheel', title: 'Feedback Flywheel', meta: 'Rahul Garg · April 2026', time: '17:05' },
    { slug: 'the-primitive-is-the-product', title: 'The primitive is the product', meta: 'Lenny Pruss · June 2025', time: '9:47' },
    { slug: 'on-idea-generation', title: 'On Exercising the Idea Muscle', meta: 'Sankalp · June 2026', time: '18:14' },
    { slug: 'prompt-injection-as-role-confusion', title: 'A Theory of Prompt Injection (and Why You Should Study Roles)', meta: 'Charles Ye et al. · June 2026', time: '9:45' },
    { slug: 'why-ai-hasnt-replaced-software-engineers', title: 'Why AI hasn\'t replaced software engineers, and won\'t', meta: 'Narayanan & Kapoor · June 2026', time: '14:05' },
    { slug: 'agent-context', title: 'Agent Context', meta: 'Sankalp · June 2026', time: '6:21' },
    { slug: 'policy-on-the-ai-exponential', title: 'Policy on the AI Exponential', meta: 'Dario Amodei · June 2026', time: '16:47' },
    { slug: 'loop-engineering', title: 'Loop Engineering', meta: 'Addy Osmani · June 2026', time: '10:40' },
    { slug: 'my-ai-adoption-journey', title: 'My AI Adoption Journey', meta: 'Mitchell Hashimoto · 2025 · 11 min', time: '10:47' },
    { slug: 'what-is-code', title: 'What Is Code?', meta: 'Srujana Pundi · May 2026', time: '7:50' },
    { slug: 'conductors-to-orchestrators', title: 'Conductors to Orchestrators: The Future of Agentic Coding', meta: 'Addy Osmani · November 2025', time: '27:39' },
    { slug: '80-problem-agentic-coding', title: 'The 80% Problem in Agentic Coding', meta: 'Addy Osmani · January 2026', time: '20:47' },
    { slug: 'human-ai', title: 'AI and the Human Voice', meta: 'Giles Thomas · March 2026', time: '5:49' },
    { slug: 'absurd-workflows', title: 'Absurd Workflows: Durable Execution With Just Postgres', meta: 'Armin Ronacher · November 2025', time: '3:39' },
    { slug: 'syntaqlite-ai', title: 'Eight Years of Wanting, Three Months of Building with AI', meta: 'Lalit Maganti · April 2026', time: '20:40' },
    { slug: 'components-of-a-coding-agent', title: 'Components of A Coding Agent', meta: 'Sebastian Raschka · April 2026', time: '11:59' },
];
